#!/bin/bash
# Enable Full Ferrari mode - GT always-on automation
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GT_ROOT="$SCRIPT_DIR/.."

echo "=== Enabling Full Ferrari Mode ==="
echo ""

# 1. Create environment file
ENV_FILE="$HOME/.gt-ferrari.env"
cat > "$ENV_FILE" << 'EOF'
# Full Ferrari Mode - GT Always-On Automation
# Generated by enable-full-ferrari.sh

# Auto-sling work to polecats (enabled by default)
export GT_AUTO_SLING=1

# Auto-create beads from prompts
export GT_AUTO_BEAD=1

# Auto-convoy for batch work
export GT_AUTO_CONVOY=1

# Compute-aware routing
export GT_COMPUTE_ROUTING=1

# Polecat pool settings (per rig)
export GT_MIN_POLECAT_POOL=3
export GT_MAX_POLECAT_POOL=5

# Enable polecat pool management
export GT_POLECAT_POOL_ENABLED=true
EOF

echo "[1/4] Created $ENV_FILE"

# 2. Source in bashrc if not already
if ! grep -q "gt-ferrari.env" "$HOME/.bashrc" 2>/dev/null; then
    echo "" >> "$HOME/.bashrc"
    echo "# Full Ferrari Mode - GT automation" >> "$HOME/.bashrc"
    echo "[ -f ~/.gt-ferrari.env ] && source ~/.gt-ferrari.env" >> "$HOME/.bashrc"
    echo "[2/4] Added to ~/.bashrc"
else
    echo "[2/4] Already in ~/.bashrc"
fi

# 3. Source now for current session
source "$ENV_FILE"
echo "[3/4] Sourced environment variables"

# 4. Install and start systemd service
if [[ -f "$GT_ROOT/scripts/install-daemon-service.sh" ]]; then
    echo "[4/4] Installing systemd service..."
    bash "$GT_ROOT/scripts/install-daemon-service.sh"
else
    echo "[4/4] Systemd service script not found, skipping..."
    echo "      Run manually: gt daemon start"
fi

echo ""
echo "=== Full Ferrari Mode Enabled ==="
echo ""
echo "Status:"
gt status 2>/dev/null || echo "  (gt status unavailable)"
echo ""
echo "Create work with:    bd create --title 'Your task'"
echo "Watch progress with: gt convoy list"
echo "Disable with:        $GT_ROOT/scripts/disable-full-ferrari.sh"
